[package]
  cjc-version = "1.0.0"
  name = "dgengine"
  description = "DGEngine game engine"
  version = "1.2.1"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}

[dependencies]
  cenum = { path = "../cenum" }
  cjsfml = { path = "../cjsfml" }
  ctemplate = { path = "../ctemplate" }
  customiterators = { path = "../customiterators" }
  endian = { path = "../endian" }

[ffi.c]
  physfs = { path = "../physfs" }

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["../stdx/linux_x86_64_llvm/dynamic/stdx"]

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["../stdx/windows_x86_64_llvm/dynamic/stdx"]
